import { WebsiteTemplateSlug } from "@/lib/sites/types";
import {
  IndustryOperationMode,
  IndustryOperationsBlueprint,
  IndustrySchedulingMode,
  PricingMode,
  StaffAllocationMode,
} from "@/lib/industry/operations-types";

export const industryOperationsBlueprints: Record<
  WebsiteTemplateSlug,
  IndustryOperationsBlueprint
> = {
  taxi: {
    industrySlug: "taxi",
    publicActionLabel: "Request quote or booking",
    primaryCustomerFlow:
      "Customer views taxi demo, customises their draft, starts setup, and later submits route-based quote/booking requests with operator review and allocation.",
    operationMode: IndustryOperationMode.QUOTE_REQUEST,
    schedulingMode: IndustrySchedulingMode.ROUTE_BASED,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.DISTANCE_TIME_BASED,
    customerPortalFeatures: [
      "View quote/booking requests and statuses",
      "Accept or decline quoted journeys",
      "View upcoming and past journeys",
      "Request cancellation or changes",
      "Notification preferences (email confirmations)",
    ],
    businessAdminFeatures: [
      "Quote inbox and status workflow",
      "Pricing settings (manual, route estimate, airport fixed fares, uplifts)",
      "Driver allocation and assignment tracking",
      "Journey calendar and dispatch board",
      "Payment status and income records",
    ],
    requiredServiceFields: [
      "Journey type",
      "Pickup address",
      "Destination",
      "Pickup date/time",
      "Passenger count",
      "Contact name",
      "Contact email",
      "Contact phone",
    ],
    optionalServiceFields: [
      "Return journey details",
      "Multi-stop notes",
      "Airport flight number",
      "Luggage count",
      "Child seat/accessibility notes",
      "Corporate reference",
    ],
    bookingOrRequestFields: [
      "Journey notes",
      "Quote status",
      "Payment status",
      "Assigned driver",
      "Assigned vehicle",
    ],
    jobLifecycleStages: [
      "DRAFT/REQUESTED",
      "REVIEWING",
      "QUOTED",
      "ACCEPTED",
      "PAYMENT_PENDING",
      "CONFIRMED",
      "DRIVER_ASSIGNED",
      "IN_PROGRESS",
      "COMPLETED",
      "CANCELLED",
      "NO_SHOW",
    ],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: [
      "Supports local private hire, airport transfer, corporate, golf transfer, tourist tour, and event transport request patterns.",
      "Pricing engine and driver app are future implementation areas; this blueprint documents shared-platform requirements only.",
    ],
  },
  "bus-hire": {
    industrySlug: "bus-hire",
    publicActionLabel: "Request bus hire quote",
    primaryCustomerFlow:
      "Customer submits group transport details (route/date/group size) and receives operator follow-up quote/availability confirmation.",
    operationMode: IndustryOperationMode.QUOTE_REQUEST,
    schedulingMode: IndustrySchedulingMode.ROUTE_BASED,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.QUOTE_BASED,
    customerPortalFeatures: [
      "Track quote and booking status",
      "View confirmed transport details",
      "Request updates to date/time or route",
    ],
    businessAdminFeatures: [
      "Quote triage and status workflow",
      "Fleet/staff allocation support",
      "Group booking timeline visibility",
      "Payment status tracking placeholder",
    ],
    requiredServiceFields: [
      "Service type",
      "Pickup location",
      "Destination",
      "Preferred date/time",
      "Contact details",
    ],
    optionalServiceFields: [
      "Group size",
      "Stops and route notes",
      "Return journey details",
      "Accessibility notes",
    ],
    bookingOrRequestFields: [
      "Quote status",
      "Assigned staff",
      "Payment status",
      "Operational notes",
    ],
    jobLifecycleStages: [
      "REQUESTED",
      "REVIEWING",
      "QUOTED",
      "ACCEPTED",
      "SCHEDULED",
      "IN_PROGRESS",
      "COMPLETED",
      "CANCELLED",
    ],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: [
      "Designed for coach/bus group transport operators with quote-led conversion flow.",
      "No live dispatch or map automation in current local/mock version.",
    ],
  },
  barbers: {
    industrySlug: "barbers",
    publicActionLabel: "Book appointment",
    primaryCustomerFlow: "Customer picks service, preferred barber, and a slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.CUSTOMER_SELECTS,
    pricingMode: PricingMode.FIXED_SERVICE_PRICE,
    customerPortalFeatures: ["View upcoming appointments", "Reschedule/cancel where allowed", "Booking confirmations"],
    businessAdminFeatures: ["Service and price management", "Staff rota", "Daily appointment board", "Job completion"],
    requiredServiceFields: ["Service", "Date/time"],
    optionalServiceFields: ["Barber preference", "Style notes"],
    bookingOrRequestFields: ["Customer name", "Phone", "Email"],
    jobLifecycleStages: ["Booked", "Checked in", "In service", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Fast turnover appointments benefit from clear slot handling."],
  },
  hairdressers: {
    industrySlug: "hairdressers",
    publicActionLabel: "Book consultation or appointment",
    primaryCustomerFlow: "Customer selects service and books a stylist slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.CUSTOMER_SELECTS,
    pricingMode: PricingMode.FROM_PRICE,
    customerPortalFeatures: ["Appointments list", "Service notes", "Message history"],
    businessAdminFeatures: ["Stylist calendars", "Service durations", "Consultation workflow", "Income dashboard"],
    requiredServiceFields: ["Service", "Date/time"],
    optionalServiceFields: ["Stylist preference", "Hair length", "Colour history"],
    bookingOrRequestFields: ["Name", "Phone", "Email", "Notes"],
    jobLifecycleStages: ["Booked", "Consulted", "In service", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Consultation pre-checks are useful for higher-value services."],
  },
  beauticians: {
    industrySlug: "beauticians",
    publicActionLabel: "Book treatment",
    primaryCustomerFlow: "Customer chooses a treatment and requests an appointment slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.FIXED_SERVICE_PRICE,
    customerPortalFeatures: ["Appointment management", "Treatment reminders", "Messaging"],
    businessAdminFeatures: ["Treatment catalogue", "Therapist allocation", "Slot buffers", "Completion logs"],
    requiredServiceFields: ["Treatment", "Date/time"],
    optionalServiceFields: ["Therapist preference", "Allergy note"],
    bookingOrRequestFields: ["Name", "Email", "Phone"],
    jobLifecycleStages: ["Booked", "Confirmed", "In treatment", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Treatment prep notes can be captured as optional fields."],
  },
  "nail-salon": {
    industrySlug: "nail-salon",
    publicActionLabel: "Book nail appointment",
    primaryCustomerFlow: "Customer chooses service and books an available slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.FIXED_SERVICE_PRICE,
    customerPortalFeatures: ["Appointment list", "Reminder messages", "Basic profile updates"],
    businessAdminFeatures: ["Service menu", "Technician assignment", "No-show tracking", "Revenue records"],
    requiredServiceFields: ["Service", "Date/time"],
    optionalServiceFields: ["Design notes", "Preferred technician"],
    bookingOrRequestFields: ["Name", "Phone", "Email"],
    jobLifecycleStages: ["Booked", "Checked in", "In service", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Simple fixed-price service selection is usually enough for launch."],
  },
  massage: {
    industrySlug: "massage",
    publicActionLabel: "Book massage session",
    primaryCustomerFlow: "Customer selects session type and books a therapist slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.FIXED_SERVICE_PRICE,
    customerPortalFeatures: ["View sessions", "Reschedule options", "Session confirmations"],
    businessAdminFeatures: ["Therapist schedules", "Room availability", "Session completion", "Income tracking"],
    requiredServiceFields: ["Session type", "Duration", "Date/time"],
    optionalServiceFields: ["Pressure preference", "Focus area", "Health notes"],
    bookingOrRequestFields: ["Name", "Phone", "Email"],
    jobLifecycleStages: ["Booked", "Confirmed", "In session", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Duration-based slots and prep notes are common needs."],
  },
  "window-cleaning": {
    industrySlug: "window-cleaning",
    publicActionLabel: "Request quote",
    primaryCustomerFlow: "Customer submits property details and requests a quote/job visit.",
    operationMode: IndustryOperationMode.QUOTE_REQUEST,
    schedulingMode: IndustrySchedulingMode.FLEXIBLE_JOB_WINDOW,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.QUOTE_BASED,
    customerPortalFeatures: ["Track quote status", "View scheduled visit windows", "Service history"],
    businessAdminFeatures: ["Route planning", "Recurring jobs", "Crew allocation", "Completion messages"],
    requiredServiceFields: ["Address", "Property type", "Frequency"],
    optionalServiceFields: ["Photos", "Access notes", "Conservatory details"],
    bookingOrRequestFields: ["Name", "Phone", "Email", "Preferred day"],
    jobLifecycleStages: ["Requested", "Quoted", "Scheduled", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Route efficiency and recurring cycles are key for operations."],
  },
  "dog-grooming": {
    industrySlug: "dog-grooming",
    publicActionLabel: "Book grooming appointment",
    primaryCustomerFlow: "Customer provides pet details and books an available slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.FIXED_TIME_SLOT,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.FROM_PRICE,
    customerPortalFeatures: ["Pet booking history", "Appointment reminders", "Request changes"],
    businessAdminFeatures: ["Groom package pricing", "Staff assignment", "Breed/time planning", "Completion records"],
    requiredServiceFields: ["Service", "Dog breed/size", "Date/time"],
    optionalServiceFields: ["Temperament notes", "Coat condition", "Add-on services"],
    bookingOrRequestFields: ["Owner name", "Phone", "Email"],
    jobLifecycleStages: ["Booked", "Checked in", "In grooming", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Breed and coat data support better slot estimates."],
  },
  "driving-instructors": {
    industrySlug: "driving-instructors",
    publicActionLabel: "Book lesson",
    primaryCustomerFlow: "Learner selects lesson type and requests a lesson slot.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.LESSON_SLOT,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.PACKAGE_BASED,
    customerPortalFeatures: ["Lesson timetable", "Package balance overview", "Message instructor"],
    businessAdminFeatures: ["Instructor calendars", "Pickup area checks", "Package sales tracking", "Progress notes"],
    requiredServiceFields: ["Lesson type", "Licence status", "Availability window"],
    optionalServiceFields: ["Pickup area", "Test date", "Learning goals"],
    bookingOrRequestFields: ["Learner name", "Phone", "Email"],
    jobLifecycleStages: ["Requested", "Scheduled", "Lesson complete", "Follow-up planned"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Lesson progression and package tracking are common requirements."],
  },
  tutors: {
    industrySlug: "tutors",
    publicActionLabel: "Book tutoring session",
    primaryCustomerFlow:
      "Customer selects tutoring service and preferred lesson slot, then submits student/parent contact details.",
    operationMode: IndustryOperationMode.BOOKING,
    schedulingMode: IndustrySchedulingMode.LESSON_SLOT,
    staffAllocationMode: StaffAllocationMode.CUSTOMER_SELECTS,
    pricingMode: PricingMode.FIXED_SERVICE_PRICE,
    customerPortalFeatures: [
      "View upcoming lessons",
      "Reschedule/cancel requests",
      "Lesson history overview",
    ],
    businessAdminFeatures: [
      "Subject/service management",
      "Tutor rota and lesson slots",
      "Tutor assignment controls",
      "Lesson completion tracking",
    ],
    requiredServiceFields: ["Tutoring service", "Date/time", "Contact details"],
    optionalServiceFields: ["Preferred tutor", "Learning goals", "Student year group"],
    bookingOrRequestFields: ["Name", "Phone", "Email", "Notes"],
    jobLifecycleStages: ["BOOKED", "CONFIRMED", "IN_SESSION", "COMPLETED"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: [
      "Supports one-to-one, online, exam prep, and group tutoring session workflows.",
    ],
  },
  "mobile-valeting": {
    industrySlug: "mobile-valeting",
    publicActionLabel: "Request valeting booking",
    primaryCustomerFlow: "Customer selects package, location, and preferred visit window.",
    operationMode: IndustryOperationMode.JOB_REQUEST,
    schedulingMode: IndustrySchedulingMode.FLEXIBLE_JOB_WINDOW,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.PACKAGE_BASED,
    customerPortalFeatures: ["Booking status", "Package history", "Service confirmations"],
    businessAdminFeatures: ["Mobile team allocation", "Area routing", "Upsell package management", "Income records"],
    requiredServiceFields: ["Valet package", "Vehicle type", "Address", "Preferred date"],
    optionalServiceFields: ["Interior add-ons", "Water/electric access", "Notes"],
    bookingOrRequestFields: ["Name", "Phone", "Email"],
    jobLifecycleStages: ["Requested", "Confirmed", "On route", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Route windows and package tiers usually drive scheduling."],
  },
  cleaners: {
    industrySlug: "cleaners",
    publicActionLabel: "Request cleaning service",
    primaryCustomerFlow: "Customer submits property and frequency details for booking/quote.",
    operationMode: IndustryOperationMode.JOB_REQUEST,
    schedulingMode: IndustrySchedulingMode.FLEXIBLE_JOB_WINDOW,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.HOURLY,
    customerPortalFeatures: ["Service request history", "Upcoming visits", "Messages and notes"],
    businessAdminFeatures: ["Cleaner allocation", "Recurring schedules", "Job completion logs", "Financial tracking"],
    requiredServiceFields: ["Property type", "Bedrooms/bathrooms", "Frequency", "Preferred date"],
    optionalServiceFields: ["Supplies provided", "Key access notes", "Deep-clean extras"],
    bookingOrRequestFields: ["Name", "Phone", "Email", "Address"],
    jobLifecycleStages: ["Requested", "Quoted/Booked", "Scheduled", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["Recurring plans and staff coverage are the core operational needs."],
  },
  gardeners: {
    industrySlug: "gardeners",
    publicActionLabel: "Request gardening job",
    primaryCustomerFlow: "Customer submits job details, photos, and preferred timing window.",
    operationMode: IndustryOperationMode.JOB_REQUEST,
    schedulingMode: IndustrySchedulingMode.FLEXIBLE_JOB_WINDOW,
    staffAllocationMode: StaffAllocationMode.BUSINESS_ALLOCATES,
    pricingMode: PricingMode.QUOTE_BASED,
    customerPortalFeatures: ["Track job requests", "View scheduled visits", "Message updates"],
    businessAdminFeatures: ["Job triage", "Crew allocation", "Seasonal schedule planning", "Completion and billing records"],
    requiredServiceFields: ["Job type", "Garden size", "Address", "Preferred timing"],
    optionalServiceFields: ["Photos", "Waste removal", "Recurring or one-off"],
    bookingOrRequestFields: ["Name", "Phone", "Email", "Access notes"],
    jobLifecycleStages: ["Requested", "Assessed", "Scheduled", "Completed"],
    completionMessageEnabled: true,
    reviewRequestRecommended: true,
    analyticsRecommended: true,
    financialTrackingRecommended: true,
    notes: ["On-site assessment and flexible scheduling are common."],
  },
};
